[I 09:42:09.496 LabApp] JupyterLab extension loaded from /home/tikim/anaconda3/lib/python3.8/site-packages/jupyterlab
[I 09:42:09.497 LabApp] JupyterLab application directory is /home/tikim/anaconda3/share/jupyter/lab
[I 09:42:09.501 LabApp] Serving notebooks from local directory: /home/tikim/work/hello-world
[I 09:42:09.501 LabApp] Jupyter Notebook 6.2.0 is running at:
[I 09:42:09.501 LabApp] http://localhost:8080/
[I 09:42:09.502 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 09:43:17.346 LabApp] 302 GET / (127.0.0.1) 0.960000ms
[I 09:43:17.365 LabApp] 302 GET /lab? (127.0.0.1) 1.460000ms
[I 09:43:21.963 LabApp] 302 POST /login?next=%2Flab%3F (127.0.0.1) 1.920000ms
[W 09:43:23.508 LabApp] Could not determine jupyterlab build status without nodejs
[W 09:43:25.890 LabApp] 404 GET /terminals/websocket/2 (127.0.0.1) 26.580000ms referer=None
[W 09:43:26.086 LabApp] 404 GET /terminals/websocket/2 (127.0.0.1) 1.810000ms referer=None
[W 09:43:26.659 LabApp] 404 GET /api/contents/work/hello-world/korean?1616373806637 (127.0.0.1): No such file or directory: work/hello-world/korean
[W 09:43:26.659 LabApp] No such file or directory: work/hello-world/korean
[W 09:43:26.659 LabApp] 404 GET /api/contents/work/hello-world/korean?1616373806637 (127.0.0.1) 1.530000ms referer=http://localhost:8080/lab?
[W 09:44:47.465 LabApp] 400 GET /api/contents/root/RPV_1400-1.root?format=text&type=file&content=1&1616373881221 (127.0.0.1): /home/tikim/work/hello-world/root/RPV_1400-1.root is not UTF-8 encoded
[W 09:44:47.466 LabApp] /home/tikim/work/hello-world/root/RPV_1400-1.root is not UTF-8 encoded
[W 09:44:47.466 LabApp] 400 GET /api/contents/root/RPV_1400-1.root?format=text&type=file&content=1&1616373881221 (127.0.0.1) 6222.280000ms referer=http://localhost:8080/lab?
[I 09:44:47.509 LabApp] Creating new notebook in /root
[I 09:44:48.149 LabApp] Kernel started: 67b6a91f-4806-4158-863f-b88716083f59, name: root
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:44:51.132 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:44:54.139 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:44:57.148 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:45:00.155 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:45:03.165 LabApp] KernelRestarter: restart failed
[W 09:45:03.165 LabApp] Kernel 67b6a91f-4806-4158-863f-b88716083f59 died, removing from map.
[I 09:45:29.065 LabApp] Creating new notebook in /root
[I 09:45:29.377 LabApp] Kernel started: 19e37048-557a-4f83-b87f-80c54e15b013, name: root
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:45:32.377 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:45:35.386 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:45:38.392 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:45:41.401 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:45:44.410 LabApp] KernelRestarter: restart failed
[W 09:45:44.410 LabApp] Kernel 19e37048-557a-4f83-b87f-80c54e15b013 died, removing from map.
[W 09:45:45.003 LabApp] 404 GET /api/kernels/19e37048-557a-4f83-b87f-80c54e15b013/channels?session_id=6e4d6399-f03b-4804-9a3b-ebad16cec8ce (127.0.0.1): Kernel does not exist: 19e37048-557a-4f83-b87f-80c54e15b013
[W 09:45:45.004 LabApp] 404 GET /api/kernels/19e37048-557a-4f83-b87f-80c54e15b013/channels?session_id=6e4d6399-f03b-4804-9a3b-ebad16cec8ce (127.0.0.1) 4.840000ms referer=None
[W 09:45:48.200 LabApp] Timeout waiting for kernel_info reply from 67b6a91f-4806-4158-863f-b88716083f59
[E 09:45:48.202 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 67b6a91f-4806-4158-863f-b88716083f59)
[E 09:45:48.203 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 67b6a91f-4806-4158-863f-b88716083f59)
[I 09:45:53.250 LabApp] Kernel started: 01338f00-5455-4b3b-b154-0c5fe5ac9678, name: root
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:45:56.251 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:45:59.259 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:46:01.284 LabApp] delete /root/Untitled1.ipynb
[I 09:46:02.266 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:46:05.274 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:46:08.284 LabApp] KernelRestarter: restart failed
[W 09:46:08.284 LabApp] Kernel 01338f00-5455-4b3b-b154-0c5fe5ac9678 died, removing from map.
[W 09:46:29.453 LabApp] Timeout waiting for kernel_info reply from 19e37048-557a-4f83-b87f-80c54e15b013
[E 09:46:29.454 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 19e37048-557a-4f83-b87f-80c54e15b013)
[E 09:46:29.455 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 19e37048-557a-4f83-b87f-80c54e15b013)
[W 09:46:53.328 LabApp] Timeout waiting for kernel_info reply from 01338f00-5455-4b3b-b154-0c5fe5ac9678
[E 09:46:53.329 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 01338f00-5455-4b3b-b154-0c5fe5ac9678)
[E 09:46:53.330 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 01338f00-5455-4b3b-b154-0c5fe5ac9678)
[I 09:47:22.214 LabApp] Kernel started: 80a31465-cdb3-4860-a69f-faba895c2e65, name: root
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:47:25.213 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:47:28.221 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:47:31.230 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:47:34.237 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:47:37.245 LabApp] KernelRestarter: restart failed
[W 09:47:37.245 LabApp] Kernel 80a31465-cdb3-4860-a69f-faba895c2e65 died, removing from map.
[I 09:47:46.701 LabApp] Saving file at /root/Untitled.ipynb
[I 09:48:00.787 LabApp] Kernel started: 112443da-de04-40a8-b00c-c4aa6d58fe12, name: root
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:48:03.788 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:48:06.797 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:48:09.805 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:48:12.814 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:48:15.822 LabApp] KernelRestarter: restart failed
[W 09:48:15.822 LabApp] Kernel 112443da-de04-40a8-b00c-c4aa6d58fe12 died, removing from map.
[W 09:48:22.277 LabApp] Timeout waiting for kernel_info reply from 80a31465-cdb3-4860-a69f-faba895c2e65
[E 09:48:22.278 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 80a31465-cdb3-4860-a69f-faba895c2e65)
[E 09:48:22.279 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 80a31465-cdb3-4860-a69f-faba895c2e65)
[I 09:48:29.465 LabApp] Kernel started: 28610cb0-5f4c-4fd7-9994-6289dc4c7dc1, name: python3
[I 09:48:43.842 LabApp] Kernel shutdown: 28610cb0-5f4c-4fd7-9994-6289dc4c7dc1
[I 09:48:44.094 LabApp] Kernel started: 5aa048df-abca-4e22-9744-da3b4d70941d, name: root
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:48:47.096 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:48:50.104 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:48:53.113 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:48:56.121 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:48:59.128 LabApp] KernelRestarter: restart failed
[W 09:48:59.128 LabApp] Kernel 5aa048df-abca-4e22-9744-da3b4d70941d died, removing from map.
[W 09:49:00.886 LabApp] Timeout waiting for kernel_info reply from 112443da-de04-40a8-b00c-c4aa6d58fe12
[E 09:49:00.887 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 112443da-de04-40a8-b00c-c4aa6d58fe12)
[E 09:49:00.888 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 112443da-de04-40a8-b00c-c4aa6d58fe12)
[W 09:49:44.141 LabApp] Timeout waiting for kernel_info reply from 5aa048df-abca-4e22-9744-da3b4d70941d
[E 09:49:44.142 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 5aa048df-abca-4e22-9744-da3b4d70941d)
[I 09:49:46.809 LabApp] Saving file at /root/testroot.ipynb
[I 09:49:54.185 LabApp] Kernel started: 70b96aeb-0e55-4a86-a44d-74b9a146aceb, name: root
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:49:57.185 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:50:00.193 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:50:03.202 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:50:06.210 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:50:06.526 LabApp] Kernel restarted: 70b96aeb-0e55-4a86-a44d-74b9a146aceb
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:50:09.528 LabApp] KernelRestarter: restart failed
[W 09:50:09.528 LabApp] Kernel 70b96aeb-0e55-4a86-a44d-74b9a146aceb died, removing from map.
[W 09:50:09.528 LabApp] Restarting kernel failed: 70b96aeb-0e55-4a86-a44d-74b9a146aceb
Future exception was never retrieved
future: <Future finished exception=RuntimeError('Restart failed')>
RuntimeError: Restart failed
[W 09:50:54.233 LabApp] Timeout waiting for kernel_info reply from 70b96aeb-0e55-4a86-a44d-74b9a146aceb
[E 09:50:54.234 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 70b96aeb-0e55-4a86-a44d-74b9a146aceb)
[E 09:50:54.235 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 70b96aeb-0e55-4a86-a44d-74b9a146aceb)
[I 09:51:08.812 LabApp] Saving file at /root/testroot.ipynb
[W 09:51:11.427 LabApp] Notebook root/testroot.ipynb is not trusted
[I 09:51:11.783 LabApp] Kernel started: f1ecc00b-7c4c-4908-9fb6-116649d06034, name: root
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:51:14.782 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:51:17.791 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:51:20.801 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:51:23.809 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:51:26.817 LabApp] KernelRestarter: restart failed
[W 09:51:26.818 LabApp] Kernel f1ecc00b-7c4c-4908-9fb6-116649d06034 died, removing from map.
[I 09:51:43.788 LabApp] Kernel started: b00e1f29-6d5d-43da-9217-653fa57ef20b, name: python3
[I 09:51:51.095 LabApp] Kernel shutdown: b00e1f29-6d5d-43da-9217-653fa57ef20b
[I 09:51:51.339 LabApp] Kernel started: 6b7cf0d4-d5c1-48ce-b357-fd51396cb5d9, name: root
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:51:54.341 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:51:57.350 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:52:00.358 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[I 09:52:03.368 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/root_v6_18_02/build/lib/JupyROOT/__init__.py", line 1, in <module>
    from JupyROOT.helpers import cppcompleter, utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/cppcompleter.py", line 8, in <module>
    from JupyROOT.helpers import utils
  File "/home/root_v6_18_02/build/lib/JupyROOT/helpers/utils.py", line 21, in <module>
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
[W 09:52:06.376 LabApp] KernelRestarter: restart failed
[W 09:52:06.376 LabApp] Kernel 6b7cf0d4-d5c1-48ce-b357-fd51396cb5d9 died, removing from map.
[W 09:52:11.830 LabApp] Timeout waiting for kernel_info reply from f1ecc00b-7c4c-4908-9fb6-116649d06034
[E 09:52:11.831 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: f1ecc00b-7c4c-4908-9fb6-116649d06034)
[E 09:52:11.831 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: f1ecc00b-7c4c-4908-9fb6-116649d06034)
[W 09:52:51.437 LabApp] Timeout waiting for kernel_info reply from 6b7cf0d4-d5c1-48ce-b357-fd51396cb5d9
[E 09:52:51.438 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 6b7cf0d4-d5c1-48ce-b357-fd51396cb5d9)
[W 09:52:51.506 LabApp] 404 GET /api/kernels/6b7cf0d4-d5c1-48ce-b357-fd51396cb5d9/channels?session_id=a1ce4196-4c3e-4e9f-8809-a32e13728a60 (127.0.0.1): Kernel does not exist: 6b7cf0d4-d5c1-48ce-b357-fd51396cb5d9
[W 09:52:51.508 LabApp] 404 GET /api/kernels/6b7cf0d4-d5c1-48ce-b357-fd51396cb5d9/channels?session_id=a1ce4196-4c3e-4e9f-8809-a32e13728a60 (127.0.0.1) 4.310000ms referer=None
[W 09:52:52.926 LabApp] Replacing stale connection: 6b7cf0d4-d5c1-48ce-b357-fd51396cb5d9:a1ce4196-4c3e-4e9f-8809-a32e13728a60
[I 09:53:11.964 LabApp] Saving file at /root/testroot.ipynb
[E 09:58:33.814 LabApp] Kernel info request failed, assuming current {}
[E 10:12:39.829 LabApp] Kernel info request failed, assuming current {}
[E 10:53:04.486 LabApp] Kernel info request failed, assuming current {}
[E 10:58:14.067 LabApp] Kernel info request failed, assuming current {}
